services:
  # quick console:
  # docker compose exec -it mysql mysql -udevuser -pdevpass devdb
  mysql:
    image: mysql:8.0
    pull_policy: weekly
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devrootpassword
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
